language: java
jdk: openjdk8
services:
- docker
script:
- mvn package -Dmaven.test.skip=true -Ddockerfile.tag=$TRAVIS_TAG dockerfile:build
deploy:
  provider: script
  script: bash docker_push
env:
  matrix:
  - secure: BN3/CL4kL4jqTZmwP9Hbz1ox4jJRRBbpVbmz2TNfgqrv4FpV0pKQVDNGBVjUwT12lQlSVVUQa9lJ1IuCIxASFgyer4NI5KYBVeWKZSTw8nX43JppyKZByS3+uuFPHgUzjVWztBKl8y8ufAMwOUxj09BsZtLbBoH9Psyy3PFSr0t5NmLgMkSTPx3LWevDG196Sk+h8x9vnfsb1t24q231Mzif0gTNROqsfE1zJR/KJv7ElBXti/KAoz5y9wjMK7W29CDemiAkkl8+Ws1sDwvRMkgBG+yBmundR+P6g6Jw6v4JzVgeiJf182sHOHd0218Udmj4fzj20hquD2C/4VtmnLcPh2SEkmWCAhO31bQPHPODstWmL3UTNajF2DudvBQy7Y32o4pvKL94F/2qv5dwAZSA2pzNuGPSBKPgdqPfMxleJe88OdFnDgb0sbo559xU6Ph6euQ3zayajEEBIChHPng3xSTwHhoDH3Etzk/GZlOGylN4sh6IG1YxmX/qtSoApHkLPwCZnBBeJSKuV4/fu8S92i1RyIaM66rYspFd0g1oItQ2TirMTP0DBiKn1rcLXy5MU7MKQNXhJBXs+Qa9xygid/qjkqJJepp3Qc3b4T0uyHD72u9KnN+NLTK7+u47T0o0+cJGDSp/ABFShIzwef8WHyxzwbJ9zRE3PQgjBwM=
  - secure: F1GfcyrxdJZzcikFDIJVWW+I6+iPFDZ/dsvaHzM9XE/mu+b4yxHfI2f9jN2TZcH+svyQ/82oQQVt5N/rEJ0s2VVOHp0nWD1hWl2XriKZ2ldditI4N5kJ7oYef7uEqfqRKYo4rSEogYEEjqooxj0/7SfeiKXeN8kYsIyKB8egVZmJOiZSVWq2+UHRYAAttCvCqI+LVhabLoJigOJZQ5LojU9r3cNRAnYYxHByOr7XaECuhfPt3i0tBShWsFo1KoTudLr6wyYFSuFl80c850LmuokeLuFiHgglu9gGd2WWBkAwyWXSkuI+f0yAGl2A0ihpO/Y51Ft0TymUSlPiMuw7UIoZGYyHEMrryf7hQ8c0PYbmREwd6rSBqpRNifQq78Q+krR5pNuEeDtF6CGt5ELcqFOWlIxaqJuz0jk9R8vqgp2djZIeBVF6JDUR8SvYYaPr1AlJgMCLi8DkkAcuZjQKrrDBzplvTNon3sxcCxhxc/RfWn29IvJ11lzrroSK6W3Mv3+hIanwa+u+nQs2kd0qJ1B0e768kzQ04dW80e3q0Nu5S0VKm5bWFdwr7lTo3eme6CLRj0Z9EPz0SNhogUaA+dWNbRsffNv2hXPG4xv+IQj8NpoBdaQkjNgqxsoA1Hm7dsNkhz/p6yurcelLOAX78sYKCi5tlzOMoSQAv/jk/KQ=
