language: java
jdk: openjdk8
services:
  - docker
script:
  - mvn package -Dmaven.test.skip=true -Ddockerfile.tag=$TRAVIS_TAG dockerfile:build
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  matrix:
    - secure: DjIpEdmwZ4QO+VQaakvM+mzJZvY7SPeeVtj+y904vuhxATfK/apklpXWA1lyVbX8FoEP4pJ054yRrrWgfZC+u8xErKhMLRHNFB5gBGjLHqtyLCkGd32r0HPNYcYYqNu58kc5aHOmt3ZBtwstBJsoLP9O8N9dYALglZIiI4Cl4VGy4djZgHaZoL9/2hgy/z4JdFhHyjKrtGy29O5pQImW1UE+oLzamGDHVqcG63qM7YW467EN5pDjMesop+2O3dF0G4ILcgpYLEFK9QC2CFW5eLRjb7gpiSRfkz9BPoJ00zmvOSSSlfijYPQow+OE7ZFtDdBUxH2yE9jKG3/eXJXoO6pb8FUK8gqf0G0DsFxWtj2O7+Ffvfr75IVoi/TeaIBrbZg9D1edn2/YhHqKbhpBgyq+HBuapU3s/ZHqsHw1kR0lY0j/Oo0qlpQDTPeTFUu810IZjqFcfHwX0jAsPgP1dBCXsVYW1ez4+YUFtUB53O+LPaH19ChpWf++U4E7dWIGeLRBBVTO0r0SsMYiY3qdQG7+uH7Q5ajQAut01LmUGvp19SpH1frfNvtK7jUa7mmLwpZu9ad5IztTpS3uAeKsCTmA/1MFQU22nk0riC3YgZlTFq8MoMKRsdDoNuf/jQheuB2+IWuLIXw4qu1oix/E5+k+/10+scEQ8okM5iTRJg4=
    - secure: Uy+5TL+GgYCc2WufTQpKO/Wv3FxLLDdfcPf5n0T6aNpWntPHioDBYWeb7vLES5T9UvhKon0Dzdt6HfnI6712eLluTZBSEmVXpRXKiuqVjPtr+WGZuW3tJiP9CdVKxuw8AJzE1d+iUoLjhVmjra7QrLm1W4xjpJi5dRDh9LjmP8oc0HOcUirxc2JHh2jEsVuVqk/P1JsyLWa8VubTKlYyKtgP+CJimt9nTpL+2Nnc6QAVm+mCN6ZJ3i2LEBHfuMNBzBDMxPywu3uaQT3lJBqJSoCof1HmiP80kiHCT0clf133FmjaGEgAX2QxhP1RCQ2VaHONy+c2Dplr4IYfEK19cjdgfJ13PZaqLjk9pB98mg3PvF4AkKo898weDnYoPrLL5uhJAGsTbjHdMJRQlpkDYlv+RU5erlYTzQc3kzf6+umd/sb0s4zl8CAZnA89nDE0U7ggsOrKr3mhN8ShvhjoulV4noKSMrDUdkygO9ynEbZCrmytpWNLTZgaJeN9JRO11L4l+38ChsrX9tIjH6g50JiVnolLTitqPo9CAJGwR1oOGSoT5RwPAw+JC6j2mmDK/Gnj2iwEPBe6CQpn5WBPDwaVLHhievfXmnINsmHEWAzOnKUKsYstr8SofmZ5wJZJtm1Zq3WS1BQhKGkhX5pqnALdjK+tT+ymuuJRS/2DkN8=
