language: java
jdk: openjdk8
services:
- docker
script:
- mvn package -Dmaven.test.skip=true -Ddockerfile.tag=$TRAVIS_TAG dockerfile:build
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  aliyun_docker_password:
    secure: CEOdRVljHQq/ToNnjdBFPv8tIin4ovztfRLmayqaeYMw/Ln1jG75SgVqPll2v/NnU8RBc7YgeLcUdxwwPY9XC703/iLc4rIjqlMNAynguwnRaJJhSxDj4QVB6BeudPSu3XHnxCK2fPwNcqQIeAGsj6m2JRi+VaoR69Y6iyhBJnmdgpCNIbO0q9/R9HHro7/A4syi2PbLId9ga7z80dvlCMcY9VVSbHByRNq99rlXQtfLHMkk2GTCzmYNFG45yxB0RwY8HRezWqk4zsgH80pdTgSfe3EARCuOaXLlMvUEnSOHR3KjD/6cCZPQ18q7ysQ92pJGfuoYDEqHcWW3v9uSTbqsRVZuc2r6CQKiMpn2W8by+hCAUkf1/+NZAT2I/dLy3TdmWoybg7h14pLK4iYGJJfJKY728fVOvJWGkD5KbX1UvDya6XAGnZPuOa5Cyo525XgC7WlWf+cAsl2UDyfecPxORDaQ0XqfJcMl32N8E/rjVpF8uP+ft6oLZ+bBJXG7tgz5lVySy17UOTC/+txPxzC6+HGE5UYtMvWiXNficaUjJaNP+bSsZEXvZy/uoW9Pl5S5t5b5wyeNd337AoP7wxwYgES3mdZ1yqx4Art3iJRKpdCvwANW5yDg7mVuFm1nvB9fABieKFvG7nQWL5f3unE7z7D9NcvE2tlNwk4TBYU=
  aliyun_docker_username:
    secure: J39/+HOShxkmej2mR23erPdOBWyjbxSHCUCUGWGvoM1z61U+eL1KqYczI5YMdggu+TamRJZA+NpydWVjqdRGmtvSiDLEUoRDmZgJ7wxzxcoqxu+mwQHr87GHpnXOuXdIDryKB7eRPYo1MjtjFSDh2b05W8PR5Gc33uwChTcrEIAUv2VpRG9Q0ammdJLTpNnCa48miCe2q5OnBBTSa4RM4ZjYahNDlp9XDMv6Us0GzG4+HeEFce7NoaFQkRwgqMS8pBYK0mO6Vosfq7jLDyBTdsEC7pn/Pi8cVZfaI2OqBW1pDrmYJn3nIV11DaMqn46rLC+EUbQigYyzwmzlnO4QHXhCl7Ouxf09A2YyK8WwHHEMVRGHhOWHEm4GnyLr5BXEJ/ox1J4htjl3m35EuextlR+V9uADEYvIIGz1V+7nGXiIPRC+ldPgKNjienRgZSof6CQ7eLYPjpkLhxesGEhQaQ+JMgiJWPeta8CGnGtRDbSYtk1fKCKtAE01wxN987zrAoGL0MimZh9U3uvTBSrkOAa27wuhn5zn9NsUzehxgJcWOwiFBhpG9aRb7jC2W6oXsqffet4q/1GsZDhA9SMrH+l/O+QbpZofBC1QO1CBJnOv9WbxkplOeDKy66tFMHdy2O63RT/jhzeCQk9qyC+UUyrVLRqL/rzutuxoxLjpEYA=
