#!/bin/bash

# aliyun docker
# echo "$ALIYUN_DOCKER_PASSWORD" | docker login -u "$ALIYUN_DOCKER_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
# docker tag kastnerorz/shu-online-judge:latest registry.cn-hangzhou.aliyuncs.com/kastnerorz/shu-online-judge:$TRAVIS_TAG
# docker push registry.cn-hangzhou.aliyuncs.com/kastnerorz/shu-online-judge:$TRAVIS_TAG

# official docker
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag kastnerorz/shu-online-judge:latest kastnerorz/shu-online-judge:$TRAVIS_TAG
docker push kastnerorz/shu-online-judge:$TRAVIS_TAG