#!/bin/bash
echo "$ALIYUN_DOCKER_PASSWORD" | docker login -u "$ALIYUN_DOCKER_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
docker tag registry.cn-hangzhou.aliyuncs.com/kastnerorz/shu-online-judge:$TRAVIS_TAG
docker push registry.cn-hangzhou.aliyuncs.com/kastnerorz/shu-online-judge:$TRAVIS_TAG